### ISSUE TITLE
ServerSelectionTimeoutError 

### ISSUE THREAD

**Issue by NiklasTR** [compstorylab/storywrangling#1]
Hi Storywrangler Team! I read your paper this morning and spent the rest of the day playing with your tool on storywrangler.org. After reading an additional paper on the concept of rank-turbulence-divergence, I thought I would give your API a try. 

After installing the package using your master branch acc. to the instruction in your README and running an example query, I end up getting repeated timeout errors by the hydra server. From first principles, do you think this is a systematic issue or something wrong on my end?  

I pasted my code below. Thank you for sharing this body of work - such a fascinating resource!

> (storywrangling) XXXX@Niklass-MacBook-Pro storywrangling % python

> Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:54:06) 
> [Clang 11.0.0 ] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> from datetime import datetime
> from storywrangling import Storywrangler

> storywrangler = Storywrangler()
> 2020-11-28 22:25:34,546 - matplotlib.font_manager - INFO - Generating new fontManager, this may take some time...
> Fontconfig warning: ignoring UTF-8: not a valid region tag
> 2020-11-28 22:25:35,152 - matplotlib.font_manager - INFO - Failed to extract font properties from /System/Library/Fonts/Apple Color Emoji.ttc: In FT2Font: Could not set the fontsize (error code 0x17)
> 2020-11-28 22:25:35,208 - matplotlib.font_manager - INFO - Failed to extract font properties from /System/Library/Fonts/LastResort.otf: tuple indices must be integers or slices, not str
> 2020-11-28 22:25:35,426 - matplotlib.font_manager - INFO - Failed to extract font properties from /System/Library/Fonts/Supplemental/NISC18030.ttf: In FT2Font: Could not set the fontsize (error code 0x17)

> storywrangler = Storywrangler()
> ngrams = ["Higgs", "#AlphaGo", "CRISPR", "#AI", "LIGO"]
> ngrams_df = storywrangler.get_ngrams_array(
> ...   ngrams,
> ...   lang="en",
> ...   database="1grams",
> ...   start_time=datetime(2010, 1, 1),
> ...   end_time=datetime(2020, 1, 1),
> ... )
> 2020-11-28 22:25:49,772 - storywrangling.api - INFO - Retrieving: 5 1grams ...
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/XXXX/Documents/GitHub/storywrangling/storywrangling/api.py", line 176, in get_ngrams_array
>     df = q.query_ngrams_array(
>   File "/Users/XXXX/Documents/GitHub/storywrangling/storywrangling/query.py", line 196, in query_ngrams_array
>     df = pd.DataFrame(list(self.database.find(query)))
>   File "/opt/anaconda3/envs/storywrangling/lib/python3.9/site-packages/pymongo/cursor.py", line 1207, in next
>     if len(self.__data) or self._refresh():
>   File "/opt/anaconda3/envs/storywrangling/lib/python3.9/site-packages/pymongo/cursor.py", line 1100, in _refresh
>     self.__session = self.__collection.database.client._ensure_session()
>   File "/opt/anaconda3/envs/storywrangling/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1816, in _ensure_session
>     return self.__start_session(True, causal_consistency=False)
>   File "/opt/anaconda3/envs/storywrangling/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1766, in __start_session
    server_session = self._get_server_session()
  File "/opt/anaconda3/envs/storywrangling/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1802, in _get_server_session
    return self._topology.get_server_session()
  File "/opt/anaconda3/envs/storywrangling/lib/python3.9/site-packages/pymongo/topology.py", line 485, in get_server_session
    self._select_servers_loop(
  File "/opt/anaconda3/envs/storywrangling/lib/python3.9/site-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: hydra.uvm.edu:27017: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 5fc2c05d9b93635a5261097f, topology_type: Single, servers: [<ServerDescription ('hydra.uvm.edu', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('hydra.uvm.edu:27017: [Errno 61] Connection refused')

**Comment by mvarnold** [comment]
Glad you found our work interesting! 

Unfortunately this repo is only for internal use for the time being. The university network professionals understandably declined our request to open the required ports, which explains the timeout errors. 

We do hope to have a workaround eventually, but in the meantime checkout the url based api at https://github.com/janeadams/storywrangler

**Comment by NiklasTR** [comment]
Hi @mvarnold - thank you for your quick response - I will look into it!
All the best!
